version: '3'
services:
  pretalx:
    image: pretalx/standalone:latest
    container_name: pretalx
    restart: unless-stopped
    depends_on: 
      - redis
      - db
    environment:
      PRETALX_FILESYSTEM_MEDIA: /public/media
      PRETALX_FILESYSTEM_STATIC: /public/static
    ports:
      - "80:80"
    volumes: 
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data
      - pretalx-public:/public
    labels:
       traefik.docker.network: "pretalxdocker"
       traefik.enable: "true"
    networks:
      - captain-overlay-network

  db:
    image: mysql:latest
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_PASSWORD: veryunsecureplschange
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - captain-overlay-network

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes: 
      - pretalx-redis:/data
    networks:
      - captain-overlay-network

volumes:
  pretalx-db:
  pretalx-data:
  pretalx-public:
  pretalx-redis:

networks:
  captain-overlay-network:
    external: true
